### ISSUE TITLE
Motivation for BUNDLE_IGNORE_CONFIG=1 in guides?

### ISSUE THREAD

**Issue by mthssdrbrg** [phusion/traveling-ruby#53]
I'm a bit curious why `BUNDLE_IGNORE_CONFIG=1` is used in the guides? I'm assuming that it can cause some kind of issue?

I've been developing a lil' [library / CLI](https://github.com/mthssdrbrg/tara) that uses Traveling Ruby and we had some issues when trying to package on of our internal applications at work that used gems from our private RubyGems server (and we have the credentials configured in the global Bundler config to avoid having them in the Gemfile). We solved it by simply removing the environment variable and everything packaged just fine.

Traveling Ruby is really great and makes it sooo much easier to create isolated archives of Ruby applications, fantastic work!

**Comment by FooBarWidget** [comment]
It is to avoid conflicts with ~/.bundle/config. While writing the tutorials, I've seen some machines on which my instructions fail because they had something in their ~/.bundle/config which conflicts with my instructions. You on the other hand have the opposite problem. I'm not sure what to do about this, but now you know why it's there.

**Comment by mthssdrbrg** [comment]
Alright, I'll just work around it where I need to, thanks for the reply!
