### ISSUE TITLE
Security vulnerability in Ruby 2.2.2 and Nokogiri <1.6.6.4. Bump and rebuild needed.

### ISSUE THREAD

**Issue by Nowaker** [phusion/traveling-ruby#60]
There's a security vulnerability in the latest Traveling Ruby. http://traveling-ruby.s3-us-west-2.amazonaws.com/list.html doesn't list any version with Ruby 2.2.3 and Nokogiri 1.6.6.4.
## MULTIPLE VULNERABILITIES IN LIBXML2, LIBXSLT

The vendored libxml2 and libxslt libraries have multiple vulnerabilities: CVE-2015-1819 CVE-2015-7941_1 CVE-2015-7941_2 CVE-2015-7942 CVE-2015-7942-2 CVE-2015-8035 CVE-2015-7995

Affected versions: All versions prior to 1.6.6.3
Fixed versions: 1.6.6.3, 1.6.7.rc4
Solution: Upgrade to latest version.
Sources: https://groups.google.com/forum/#!topic/nokogiri-talk/gEpHWo2xLCE 
https://github.com/sparklemotion/nokogiri/blob/v1.6.6.x/CHANGELOG.rdoc#1663--2015-11-16 
https://github.com/sparklemotion/nokogiri/commit/ac6106f1e641d50b27752c52b355e01d03ae8829 
https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.rdoc#167rc4--2015-11-22 
https://github.com/sparklemotion/nokogiri/commit/ee52b7be5b47e1029af98f6b7eb6df7fc5ffd359 
## UNSAFE PARSING OF UNCLOSED COMMENTS

Parsing an unclosed comment can result in Conditional jump or move depends on uninitialised value(s) and unsafe memory access.

Affected versions: All versions prior to 1.6.6.4
Fixed versions: 1.6.6.4, 1.6.7.rc4
Solution: Upgrade to latest version.
Credit: Florian Weingarten, Francois Chagnon
Sources: https://groups.google.com/forum/#!topic/nokogiri-talk/nFl0mfcJpbk 
https://github.com/sparklemotion/nokogiri/blob/v1.6.6.x/CHANGELOG.rdoc#1664--2015-11-19 
https://github.com/sparklemotion/nokogiri/commit/3ab1b2339f7bb3a00590c8d288a24a9dbfe5aec4 
https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.rdoc#167rc4--2015-11-22 
https://github.com/sparklemotion/nokogiri/commit/0948e9fa38c949661983a33752fdcb94a453e272 
## Ruby 2.2.3 Released

We are pleased to announce the release of Ruby 2.2.3. This is a TEENY version release of the stable 2.2 series.

This release includes the security fix for a RubyGems domain name verification vulnerability.
- [CVE-2015-3900 Request hijacking vulnerability in RubyGems 2.4.6 and earlier](http://blog.rubygems.org/2015/05/14/CVE-2015-3900.html)

There are also some bugfixes. See ChangeLog for details.

**Comment by FooBarWidget** [comment]
It looks like OpenSSL also just released a security advisory. I'll try to find time this weekend or next weekend to do a release.

**Comment by Nowaker** [comment]
Thanks @FooBarWidget.

**Comment by Nowaker** [comment]
More news, @FooBarWidget. Another vuln in nokogiri. We need to bundle 1.6.7.1 in Traveling Ruby.

- Affected versions: All versions with vendored libxml2 prior to 1.6.7.1
- Fixed versions: 1.6.7.1
- Solution: Upgrade to latest version.
- Sources:
  - https://groups.google.com/forum/#!topic/ruby-security-ann/aSbgDiwb24s 
  - https://github.com/sparklemotion/nokogiri/pull/1378 
  - https://github.com/sparklemotion/nokogiri/commit/4205af1a2a546f79d1b48df2ad8b27299c0099c5 
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-5312 
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-7497 
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-7498 
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-7499 
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-7500 
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8241 
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8242 
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8317

**Comment by Nowaker** [comment]
Holy cow, there's also a new Ruby version that fixes another CVE. 2.2.4.

- https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-2-4-released/
- https://www.ruby-lang.org/en/news/2015/12/16/unsafe-tainted-string-usage-in-fiddle-and-dl-cve-2015-7551/

**Comment by Nowaker** [comment]
@FooBarWidget Any chance to get 2.2.4 along with Nokogiri bump? Do you need any help with that?

**Comment by kwartel** [comment]
@Nowaker I haven't got around to making a clean pull request, but I have linux binaries.

**Comment by Nowaker** [comment]
@kwartel Maybe you could send whatever you have as PR? Doesn't have to be complete.

**Comment by kwartel** [comment]
I have to make time to make a proper pull request imo. Instead of making a pull request, I think you're better off checking my fork for now. https://github.com/kwartel/traveling-ruby

I might be able to sneak some time in next weekend to clean it all up, add the OS X bits (I have a MBP2015, so I can easily test it) and make a pull request. I will try to add 2.3.0, but if it gives any issues, I'm outie.

**Comment by Nowaker** [comment]
Thanks @kwartel. Out of curiosity, if that works for you, what's not proper about it? :-)

**Comment by kwartel** [comment]
I haven't tested it properly and I actually want to make a pull request which can be added right away. Like I said, I can provide you binaries right away.

You can also build them yourself using my branch, since you actually just need to install docker on a linux machine, clone the repo, cd into the linux folder and run `rake`, wait 15 minutes and you have your binaries.

**Comment by FooBarWidget** [comment]
Small update... in December I suffered from a minor burnout. I couldn't get anything done, so I took a month long vacation. I am feeling better now, but for the time being commercial projects require my 100% attention, so I can't say yet when I will update Traveling Ruby.

**Comment by Nowaker** [comment]
@kwartel Thanks, man. I'll give it a try.

**Comment by Nowaker** [comment]
@FooBarWidget Good to hear! Welcome "back". :-)

**Comment by prees1** [comment]
Does anyone have any updates on this? I am looking to use nokogiri 1.6.7.2

Is it possible we can create a set of steps on how to compile a specific gem (say nokogiri) so that others can help compile different versions?

**Comment by georgemillo** [comment]
+1 to @prees1's comment. I'm hoping to use Traveling Ruby with Nokogiri 1.6.8, but can't figure out how to compile the binary myself.

@kwartel: your fork doesn't seem to be online anymore. Any chance you can briefly explain the process for compiling my own binaries? I can't figure it out from the TR docs.

**Comment by georgemillo** [comment]
Some updates on my progress; hopefully this will help anyone else trying to compile their own gems and use a newer version of Nokogiri etc. with traveling Ruby.

Since I'm on a Mac, the first step was to compile on OS X. This was actually pretty straightforward:

0. Download the older version of XCode as described [here](https://github.com/phusion/traveling-ruby/tree/master/osx) (note that the 'automated way' wouldn't work for me but the 'manual way' did.)
1. Clone the traveling Ruby repo
2. `cd osx`
3. update the Gemfile(s) in `shared/gemfiles` to have the gem version numbers you want.
4. `rake`

After a very long wait, you'll have your compiled gems. (Note: if you only care about compiling them for a specific version of Ruby, open up `RUBY_VERSIONS.txt` and remove the versions you don't want before running `rake`, which will speed up the compilation.) You can package up these files into your app in the [normal way](https://github.com/phusion/traveling-ruby/blob/master/TUTORIAL-3.md)...

... except once I'd packaged my app, it would crash on startup with the error `cannot load such file -- nokogiri/nokogiri`. After many headaches, I figured out the problem by looking at the `$PATH` variable and at the directory structure of my packaged Rails app. Turns out that my compiled Nokogiri gem was living under the path `my_packaged_app/lib/vendor/ruby/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/nokogiri-1.6.8` (note the darwin_**14**), but my $PATH in Ruby was looking for the extensions under `my_packaged_app/lib/vendor/ruby/2.2.0/extensions/x86_64-darwin-13/` - note the *13* on the end.

So the problem was that I'd compiled Nokogiri on my Mac which is using a newer version of OS X than the gems in the Traveling Ruby S3 bucket were compiled on. But all I had to do was move the `nokogiri-1.6.8` dir into `x86_64-darwin-13/2.2.0-static` within my package and now it works.

Of course, I’m slightly concerned that having a mix of gems compiled on different versions of OS X might cause me problems. My package works on *my* Mac but I still need to test it on other machines. But I suppose if this causes an issue I could just compile ​_all_​ my native extensions gems manually on darwin 14 and not use any of TR’s precompiled ones (I only bothered to use 'self-compiled' versions of the gems I needed that aren't on TR yet, like Nokogiri 1.6.8.)

Now all I have to do is compile on Linux too, which is causing me a whole host of other headaches. Once more unto the breach...

**Comment by prees1** [comment]
@georgemillo thanks for sharing the steps you took! I would be really interested the steps needed on Linux and Windows if you get there! Great stuff!

**Comment by FloorD** [comment]
We're consolidating all issues concerning gems and gem support. Thank you for reporting this!
